modLoader = "javafml"
loaderVersion = "*"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "no_escape"
version = "${mod_version}"
displayName = "No Escape"
authors = "Player005" #optional

description = '''Disables leaving the world, quitting Minecraft or exiting fullscreen.'''

[[mixins]]
config = "no_escape.client.mixins.json"
